
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { Providers } from "../Redux/providers"; // import the Providers component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sigange ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers> 
          {/* wrap your components with Providers */}
          <Navbar/>
          
          {children}
        </Providers>
      </body>
    </html>
  );
}
